### ISSUE TITLE
can you give some options longer than 40s

### ISSUE THREAD

**Issue by luanwulin** [Nosskirneh/CustomLockscreenDuration#2]
40 seconds is too short
can you give some options longer than 40s, such as 5 minutes or 3 minutes?
thkx a lot

**Comment by Nosskirneh** [comment]
Hi!

I didn’t come up with the timings. It’s simply a method that takes an input and outputs a delay in a different value.


So something like:
0 = 2 seconds
1 = 5 seconds
2 = 7 seconds
3 = 14 seconds
4 = ...
5 = ...
6 = 40

40 was the lengthiest delay that was found. There might be other ways to accomplish this instead, similar to what FLEXall is doing to prevent the device from sleeping. Basically disable the timer all together and then enabling it using a timer. It’s not something I’ll be doing in this project. Feel free to submit a pull request if you’re feeling adventurous.
